repos:

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      name: Run black formatter
      language_version: python3


- repo: local
  hooks:

    - id: mypy
      name: Run mypy
      entry: mypy application --ignore-missing-imports --follow-imports=skip
      language: system
      pass_filenames: false


    - id: flask-tests
      name: Run Flask tests
      entry: bash -c "FLASK_APP=cre.py FLASK_CONFIG=test flask test"
      language: system
      pass_filenames: false


    - id: coverage-check
      name: Coverage >= 80%
      entry: bash -c "FLASK_APP=cre.py FLASK_CONFIG=test flask test --cover"
      language: system
      pass_filenames: false
