FROM python:rc-slim

# For pete's sake do not put this on the internet

RUN useradd -ms /bin/bash  credev

COPY . /home/credev/cre_sync
RUN chown -R credev:credev /home/credev/cre_sync
USER credev


WORKDIR /home/credev/cre_sync

RUN export PATH=$PATH:/home/credev/.local/bin &&\
    pip install -r requirements.txt &&\
    chmod +x docker-entrypoint.sh

ENTRYPOINT ["/home/credev/cre_sync/docker-entrypoint.sh"]



