doctype: CRE
id: 568-138
links:
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-1
    name: NIST 800-53 v5
    section: PS-1 Policy and Procedures
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-2
    name: NIST 800-53 v5
    section: PS-2 Position Risk Designation
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-3
    name: NIST 800-53 v5
    section: PS-3 Personnel Screening
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-4
    name: NIST 800-53 v5
    section: PS-4 Personnel Termination
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-5
    name: NIST 800-53 v5
    section: PS-5 Personnel Transfer
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-6
    name: NIST 800-53 v5
    section: PS-6 Access Agreements
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-7
    name: NIST 800-53 v5
    section: PS-7 External Personnel Security
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-8
    name: NIST 800-53 v5
    section: PS-8 Personnel Sanctions
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=PS-9
    name: NIST 800-53 v5
    section: PS-9 Position Descriptions
  ltype: Linked To
name: '>>Personnel Security'
