doctype: CRE
id: 284-521
links:
- document:
    doctype: CRE
    id: 724-770
    name: Authorized access
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x12-V4-Access-Control.md
    name: ASVS
    section: V4.3.3
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: Empty
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/732.html
    name: CWE
    section: '732'
    subsection: ''
    version: ''
  type: Linked To
name: Additional authorization for lower and higher value application
