doctype: CRE
id: 263-184
links:
- document:
    doctype: CRE
    id: 615-188
    name: Deployment process
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x10-V1-Architecture.md
    name: ASVS
    section: Verify that the build pipeline contains a build step to automatically
      build and verify the secure deployment of the application, particularly if the
      application infrastructure is software defined, such as cloud environment build
      scripts.
    sectionID: V1.14.4
  ltype: Linked To
name: Automate secure build and deployment, especially with SDI
