doctype: CRE
id: 233-748
links:
- document:
    doctype: CRE
    id: 636-660
    name: Technical application security controls
  ltype: Contains
- document:
    doctype: CRE
    id: 850-376
    name: Facilities management
  ltype: Related
- document:
    doctype: CRE
    id: 486-813
    name: Configuration
  ltype: Related
- document:
    doctype: CRE
    id: 180-488
    name: Proper Configuration for all applications and frameworks
  ltype: Contains
- document:
    doctype: CRE
    id: 814-322
    name: Whitelist data sources and sinks
    tags:
    - SSRF protection
  ltype: Contains
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
name: Configuration hardening
tags:
- Configuration
