doctype: CRE
id: 257-668
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: CRE
    id: 028-726
    name: XSS
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.4.3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1021.html
    name: CWE
    section: '1021'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.html
    name: (WSTG) Web Security Testing Guide
    section: WSTG-INPV-01; WSTG-INPV-02; WSTG-CLNT-01
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: Cheat_sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
- document:
    description: '"Ensure a valid setting is used on all web pages returned by your
      site (if you expect the page to be framed only by pages on your server (e.g.
      it''s part of a FRAMESET) then you''ll want to use SAMEORIGIN, otherwise if
      you never expect the page to be framed, you should use DENY.  Alternatively
      consider implementing Content Security Policy''s ''frame-ancestors'' directive."'
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: 'ZAP Rule: "X-Frame-Options Setting Malformed"'
    tags:
    - '"Passive"'
    tooltype: Offensive
  ltype: SAME
- document:
    description: '"Ensure only a single X-Frame-Options header is present in the response."'
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: 'ZAP Rule: "Multiple X-Frame-Options Header Entries"'
    tags:
    - '"Passive"'
    tooltype: Offensive
  ltype: SAME
- document:
    description: '"Ensure X-Frame-Options is set via a response header field.  Alternatively
      consider implementing Content Security Policy''s ''frame-ancestors'' directive."'
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: 'ZAP Rule: "X-Frame-Options Defined via META (Non-compliant with Spec)"'
    tags:
    - '"Passive"'
    tooltype: Offensive
  ltype: SAME
- document:
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: 'ZAP Rule: "Missing Anti-clickjacking Header"'
    tags:
    - '"Passive"'
    tooltype: Offensive
  ltype: SAME
name: Configure CSP configuration properly
tags:
- XSS
