doctype: CRE
id: 257-668
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: CRE
    id: 028-726
    name: XSS
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1021.html
    name: CWE
    section: ''
    sectionID: '1021'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
name: Configure CSP configuration properly
tags:
- XSS
