doctype: CRE
id: 065-388
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/116.html
    name: CWE
    section: ''
    sectionID: '116'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
name: Configure X-Content-Type-Options properly
