doctype: CRE
id: 257-668
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: CRE
    id: 028-726
    name: XSS
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.4.3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1021.html
    name: CWE
    section: '1021'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.html
    name: (WSTG) Web Security Testing Guide
    section: WSTG-INPV-01; WSTG-INPV-02; WSTG-CLNT-01
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: Cheat_sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
name: Configure CSP configuration properly
tags:
- XSS
