doctype: CRE
id: 257-668
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: CRE
    id: 760-765
    name: XSS protection
    tags:
    - Injection protection
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.4.3
    sectionID: Verify that a Content Security Policy (CSP) response header is in place
      that helps mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript
      injection vulnerabilities.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1021.html
    name: CWE
    section: ''
    sectionID: '1021'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting.html;
      https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.html
    name: OWASP Web Security Testing Guide (WSTG)
    section: WSTG-INPV-01; WSTG-INPV-02; WSTG-CLNT-01
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
- document:
    description: Ensure X-Frame-Options is set via a response header field.  Alternatively
      consider implementing Content Security Policy's 'frame-ancestors' directive.
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: ZAP Rule
    section: X-Frame-Options Defined via META (Non-compliant with Spec)
    sectionID: 10020-3
    tags:
    - 10020-3
    - Passive
    tooltype: Offensive
  ltype: Linked To
- document:
    description: Ensure a valid setting is used on all web pages returned by your
      site (if you expect the page to be framed only by pages on your server (e.g.
      it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you
      never expect the page to be framed, you should use DENY.  Alternatively consider
      implementing Content Security Policy's 'frame-ancestors' directive.
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: ZAP Rule
    section: X-Frame-Options Setting Malformed
    sectionID: 10020-4
    tags:
    - 10020-4
    - Passive
    tooltype: Offensive
  ltype: Linked To
- document:
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: ZAP Rule
    section: Missing Anti-clickjacking Header
    sectionID: 10020-1
    tags:
    - 10020-1
    - Passive
    tooltype: Offensive
  ltype: Linked To
- document:
    description: Ensure only a single X-Frame-Options header is present in the response.
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
    name: ZAP Rule
    section: Multiple X-Frame-Options Header Entries
    sectionID: 10020-2
    tags:
    - 10020-2
    - Passive
    tooltype: Offensive
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/103.html
    name: CAPEC
    section: Clickjacking
    sectionID: '103'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/181.html
    name: CAPEC
    section: Flash File Overlay
    sectionID: '181'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/222.html
    name: CAPEC
    section: iFrame Overlay
    sectionID: '222'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/504.html
    name: CAPEC
    section: Task Impersonation
    sectionID: '504'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/506.html
    name: CAPEC
    section: Tapjacking
    sectionID: '506'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/587.html
    name: CAPEC
    section: Cross Frame Scripting (XFS)
    sectionID: '587'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/654.html
    name: CAPEC
    section: Credential Prompt Impersonation
    sectionID: '654'
    version: '3.9'
  ltype: SAME
name: Configure CSP configuration properly
tags:
- XSS protection
