doctype: CRE
id: 036-147
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: 'Verify that a Strict-Transport-Security header is included on all responses
      and for all subdomains, such as Strict-Transport-Security: max-age=15724800;
      includeSubdomains.'
    sectionID: V14.4.5
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/523.html
    name: CWE
    section: ''
    sectionID: '523'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.html
    name: (WSTG) Web Security Testing Guide
    section: WSTG-CONF-07
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: Cheat_sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
name: Configure HSTS configuration properly
