doctype: CRE
id: 674-425
links:
- document:
    doctype: CRE
    name: Encryption algorithms
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x14-V6-Cryptography.md
    name: ASVS
    section: V6.2.3
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.html
    name: WSTG
    section: WSTG-CRYP-04
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/326.html
    name: CWE
    section: '326'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
name: Cryptographic configuration state of the art
