doctype: CRE
id: 124-564
links:
- document:
    doctype: CRE
    id: 124-564
    name: Configuration Management
    tags:
    - Configuration
  ltype: Contains
- document:
    doctype: CRE
    id: 757-271
    name: Use proper source code control system
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/cprt/catalog#/cprt/framework/version/SP_800_53_5_1_0/home?element=SA-10
    name: NIST 800-53 v5
    section: SA-10 Developer Configuration Management
  ltype: Linked To
name: Developer Configuration Management
