doctype: CRE
id: 725-682
links:
- document:
    doctype: CRE
    id: 854-643
    name: '>>Business logic'
    tags:
    - DOS
  ltype: Contains
- document:
    doctype: CRE
    id: 842-876
    name: '>>Logging and error handling'
  ltype: Related
- document:
    doctype: CRE
    id: 623-550
    name: DOS
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x19-V11-BusLogic.md
    name: ASVS
    section: V11.1.8
    sectionID: Verify that the application has configurable alerting when automated
      attacks or unusual activity is detected.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/390.html
    name: CWE
    section: ''
    sectionID: '390'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Abuse_Case_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Abuse Case Cheat Sheet
  ltype: Linked To
name: Enable configurable alert against usage anomalies
tags:
- DOS
