doctype: CRE
id: 567-755
links:
- document:
    doctype: CRE
    id: 464-513
    name: Assurance processes
  ltype: Contains
- document:
    doctype: CRE
    id: 766-162
    name: Security Analysis and documentation
  ltype: Contains
- document:
    doctype: CRE
    id: 427-113
    name: Security governance regarding people
  ltype: Contains
- document:
    doctype: CRE
    id: 563-088
    name: Security organizing processes
  ltype: Contains
name: Governance processes for security
