doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 724-770
    name: '>>Authorized access'
  type: Contains
- document:
    doctype: CRE
    id: 028-728
    name: Personal data handling
  type: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x18-V10-Malicious.md
    name: ASVS
    section: V10.2.2
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/272.html
    name: CWE
    section: '272'
    subsection: ''
    version: ''
  type: Linked To
name: Let application request minimal permissions
tags:
- Personal data handling
