doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 123-124
    name: Minimize permissions
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x18-V10-Malicious.md
    name: ASVS
    section: V10.2.2
    sectionID: Verify that the application does not ask for unnecessary or excessive
      permissions to privacy related features or sensors, such as contacts, cameras,
      microphones, or location.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/272.html
    name: CWE
    section: ''
    sectionID: '272'
  ltype: Linked To
- document:
    doctype: Standard
    name: ISO 27001
    section: Use of privileged utility programs
    sectionID: '8.18'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/17.html
    name: CAPEC
    section: Using Malicious Files
    sectionID: '17'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/35.html
    name: CAPEC
    section: Leverage Executable Code in Non-Executable Files
    sectionID: '35'
    version: '3.9'
  ltype: SAME
- document:
    doctype: Standard
    hyperlink: https://capec.mitre.org/data/definitions/76.html
    name: CAPEC
    section: Manipulating Web Input to File System Calls
    sectionID: '76'
    version: '3.9'
  ltype: SAME
name: Let application request minimal permissions
