doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 123-124
    name: Minimize permissions
  ltype: Contains
- document:
    doctype: CRE
    id: 362-550
    name: '>>Personal data handling'
    tags:
    - Security and Privacy Engineering Principles
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x18-V10-Malicious.md
    name: ASVS
    section: V10.2.2
    sectionID: Verify that the application does not ask for unnecessary or excessive
      permissions to privacy related features or sensors, such as contacts, cameras,
      microphones, or location.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/272.html
    name: CWE
    section: ''
    sectionID: '272'
  ltype: Linked To
name: Let application request minimal permissions
