doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 724-770
    name: '>>Authorized access'
  ltype: Contains
- document:
    doctype: CRE
    id: 362-550
    name: '>>Personal data handling'
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x18-V10-Malicious.md
    name: ASVS
    section: Verify that the application does not ask for unnecessary or excessive
      permissions to privacy related features or sensors, such as contacts, cameras,
      microphones, or location.
    sectionID: V10.2.2
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/272.html
    name: CWE
    section: ''
    sectionID: '272'
  ltype: Linked To
name: Let application request minimal permissions
