doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 724-770
    name: '>>Authorized access'
  ltype: Contains
- document:
    doctype: CRE
    id: 362-550
    name: '>>Personal data handling'
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/272.html
    name: CWE
    section: ''
    sectionID: '272'
  ltype: Linked To
name: Let application request minimal permissions
