doctype: CRE
id: 540-566
links:
- document:
    doctype: CRE
    id: 724-770
    name: Authorized access
  type: Contains
- document:
    doctype: CRE
    id: 362-550
    name: Personal data handling
  type: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x18-V10-Malicious.md
    name: ASVS
    section: V10.2.2
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '272'
    subsection: ''
    version: ''
  type: Linked To
name: Minimal permisions for application
