doctype: CRE
id: 530-671
links:
- document:
    doctype: CRE
    id: 634-733
    name: Communication authentication
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x10-V1-Architecture.md
    name: ASVS
    section: V1.9.2
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/295.html
    name: CWE
    section: '295'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html
    name: Cheat_sheets
    section: Transport Layer Protection Cheat Sheet
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
    name: Cheat_sheets
    section: TLS Cipher String Cheat Sheet
    subsection: ''
    version: ''
  type: Linked To
name: Mutually authenticate application components
