doctype: CRE
id: 278-413
links:
- document:
    doctype: CRE
    id: 146-556
    name: Authenticate consistently
  ltype: Contains
- document:
    doctype: CRE
    id: 155-155
    name: Architecture
  ltype: Related
- document:
    doctype: CRE
    id: 724-770
    name: '>>Authorized access'
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://owasp-top-10-proactive-controls-2018.readthedocs.io/en/latest/c3-secure-database-access.html
    name: OWASP Proactive Controls
    section: C3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/306.html
    name: CWE
    section: ''
    sectionID: '306'
  ltype: Linked To
name: Mutually authenticate application components. Minimize privileges
tags:
- Architecture
