doctype: CRE
id: 558-807
links:
- document:
    doctype: CRE
    id: 270-568
    name: Authentication mechanism
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x11-V2-Authentication.md
    name: ASVS
    section: V2.2.5
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/319.html
    name: CWE
    section: '319'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
name: Mutual authentication between credential service provider and application
tags:
- TLS
