doctype: CRE
id: 266-527
links:
- document:
    doctype: CRE
    id: 783-355
    name: Deployment
    tags:
    - Configuration
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#/control?version=5.1&number=SC-41
    name: NIST 800-53 v5
    section: SC-41 Port and I/O Device Access
  ltype: Linked To
name: Physical security
