doctype: CRE
id: 180-488
links:
- document:
    doctype: CRE
    id: 180-487
    name: Server protection
  ltype: Contains
- document:
    doctype: CRE
    id: 486-813
    name: Configuration
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/16.html
    name: CWE
    section: ''
    sectionID: '16'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
name: Proper Configuration for all applications and frameworks
tags:
- Configuration
