doctype: CRE
id: 180-488
links:
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.3
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '16'
    subsection: ''
    version: ''
  type: Linked To
name: Proper Configuration foe all applications and frameworks
