doctype: CRE
id: 257-668
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.4.3
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-INPV-01,
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-INPV-02,
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.html
    name: WSTG
    section: WSTG-CLNT-01
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1021.html
    name: CWE
    section: '1021'
    subsection: ''
    version: ''
  type: Linked To
name: Proper CSP configuration
tags:
- XSS
