doctype: CRE
id: 180-488
links:
- document:
    doctype: CRE
    id: 233-748
    name: Configuration hardening
    tags:
    - Configuration
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.3
    sectionID: Verify that server configuration is hardened as per the recommendations
      of the application server and frameworks in use.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/16.html
    name: CWE
    section: ''
    sectionID: '16'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
- document:
    description: Ensure that only POST is accepted where POST is expected.
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRule.java
    name: ZAP Rule
    section: GET for POST
    sectionID: '10058'
    tags:
    - Active
    - '10058'
    tooltype: Offensive
  ltype: Linked To
- document:
    description: Ensure that your web server, application server, load balancer, etc.
      is configured to set the Permissions-Policy header instead of the Feature-Policy
      header.
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PermissionsPolicyScanRule.java
    name: ZAP Rule
    section: Deprecated Feature Policy Header Set
    sectionID: 10063-2
    tags:
    - 10063-2
    - Passive
    tooltype: Offensive
  ltype: Linked To
name: Proper Configuration for all applications and frameworks
