doctype: CRE
id: 180-488
links:
- document:
    doctype: CRE
    name: Server protection
  type: Contains
- document:
    doctype: CRE
    id: 486-813
    name: Configuration
  type: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.3
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/16.html
    name: CWE
    section: '16'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: Cheat_sheets
    section: Docker Security Cheat Sheet
    subsection: ''
    version: ''
  type: Linked To
name: Proper Configuration for all applications and frameworks
tags:
- Configuration
