doctype: CRE
id: 462-245
links:
- document:
    doctype: CRE
    id: 613-285
    name: '>>Dependency strength'
  type: Contains
- document:
    doctype: CRE
    id: 486-813
    name: Configuration
  type: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.2.2
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1002.html
    name: CWE
    section: '1002'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/04-Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information.html
    name: WSTG
    section: WSTG-CONF-04
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: Cheat_sheets
    section: Docker Security Cheat Sheet
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Vulnerable_Dependency_Management_Cheat_Sheet.html
    name: Cheat_sheets
    section: Vulnerable Dependency Management Cheat Sheet
    subsection: ''
    version: ''
  type: Linked To
name: Remove unnecessary features, documentation, configuration etc
tags:
- Configuration
