doctype: CRE
id: 462-245
links:
- document:
    doctype: CRE
    id: 613-285
    name: '>>Dependency strength'
  ltype: Contains
- document:
    doctype: CRE
    id: 486-813
    name: Configuration
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/1002.html
    name: CWE
    section: ''
    sectionID: '1002'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Vulnerable_Dependency_Management_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Vulnerable Dependency Management Cheat Sheet
  ltype: Linked To
name: Remove unnecessary features, documentation, configuration etc
tags:
- Configuration
