doctype: CRE
id: 764-507
links:
- document:
    doctype: CRE
    name: XML Parser hardening
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md
    name: ASVS
    section: V5.5.2
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-top-ten/2017/A4_2017-XML_External_Entities_(XXE)
    name: Top10 2017
    section: A4-XML_External_Entities_(XXE)
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/07-Testing_for_XML_Injection.html
    name: WSTG
    section: WSTG-INPV-07
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/611.html
    name: CWE
    section: '611'
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/XML_Security_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: Cheat_sheets
    section: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html
    subsection: ''
    version: ''
  type: Linked To
name: Restrictive XML parsing configuration
tags:
- Configuration
