doctype: CRE
id: 515-021
links:
- document:
    doctype: CRE
    id: 726-868
    name: Deployed topology
    tags:
    - Architecture
  type: Contains
- document:
    doctype: CRE
    id: 836-068
    name: Deserialization Prevention
  type: Related
- document:
    doctype: CRE
    id: 155-155
    name: Architecture
  type: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x10-V1-Architecture.md
    name: ASVS
    section: V1.14.5
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp-top-10-proactive-controls-2018.readthedocs.io/en/latest/c5-validate-all-inputs.html
    name: OPC
    section: C5
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/265.html
    name: CWE
    section: '265'
    subsection: ''
    version: ''
  type: Linked To
name: Sandbox, containerize and/or isolate applications at the network level
tags:
- Architecture
