doctype: CRE
id: 253-452
links:
- document:
    doctype: CRE
    id: 615-188
    name: Deployment process
  type: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.1
    subsection: ''
    version: ''
  type: Linked To
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '0'
    subsection: ''
    version: ''
  type: Linked To
name: Secure and repeatable application build
