doctype: CRE
id: 253-452
links:
- document:
    doctype: CRE
    id: 615-188
    name: Deployment process
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: Verify that the application build and deployment processes are performed
      in a secure and repeatable way, such as CI / CD automation, automated configuration
      management, and automated deployment scripts.
    sectionID: V14.1.1
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: Cheat_sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
name: Securely automate build and deployment in pipeline
