doctype: CRE
id: 253-452
links:
- document:
    doctype: CRE
    id: 615-188
    name: Deployment process
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
name: Securely automate build and deployment in pipeline
