doctype: CRE
id: 347-352
links:
- document:
    doctype: CRE
    id: 473-177
    name: Deploy/build
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.5
    sectionID: Verify that authorized administrators can verify the integrity of all
      security-relevant configurations to detect tampering.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
name: Set and confirm integrity of security deployment configuration
