doctype: CRE
id: 674-425
links:
- document:
    doctype: CRE
    id: 742-432
    name: Encryption algorithms
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/326.html
    name: CWE
    section: ''
    sectionID: '326'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Cryptographic Storage Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Key Management Cheat Sheet
  ltype: Linked To
name: Use state of the art cryptographic configuration
