doctype: CRE
id: 674-425
links:
- document:
    doctype: CRE
    id: 742-432
    name: Encryption algorithms
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x14-V6-Cryptography.md
    name: ASVS
    section: V6.2.3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/326.html
    name: CWE
    section: ''
    sectionID: '326'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.html
    name: (WSTG) Web Security Testing Guide
    section: WSTG-CRYP-04
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html
    name: Cheat_sheets
    section: Cryptographic Storage Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html
    name: Cheat_sheets
    section: Key Management Cheat Sheet
  ltype: Linked To
name: Use state of the art cryptographic configuration
