"""add cascades for foreign keys

Revision ID: 455f052a44ea
Revises: 3c65127871a6
Create Date: 2022-04-03 17:40:00.616539

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "455f052a44ea"
down_revision = "3c65127871a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cre_links", schema=None) as batch_op:
        batch_op.drop_constraint("fk_crelinks_group_cre", type_="foreignkey")
        batch_op.drop_constraint("fk_crelinks_cre_cre", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_cre_links_group_cre"),
            "cre",
            ["group"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_cre_links_cre_cre"),
            "cre",
            ["cre"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("cre_node_links", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cre_node_links_cre_cre", type_="foreignkey")
        batch_op.drop_constraint("fk_cre_node_links_node_node", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_cre_node_links_cre_cre"),
            "cre",
            ["cre"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_cre_node_links_node_node"),
            "node",
            ["node"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("cre_node_links", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_cre_node_links_node_node"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_cre_node_links_cre_cre"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_cre_node_links_node_node", "node", ["node"], ["id"]
        )
        batch_op.create_foreign_key("fk_cre_node_links_cre_cre", "cre", ["cre"], ["id"])

    with op.batch_alter_table("cre_links", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_cre_links_cre_cre"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_cre_links_group_cre"), type_="foreignkey"
        )
        batch_op.create_foreign_key("fk_crelinks_cre_cre", "cre", ["cre"], ["id"])
        batch_op.create_foreign_key("fk_crelinks_group_cre", "cre", ["group"], ["id"])

    # ### end Alembic commands ###
