"""add snapshots and staging tables

Revision ID: 7d3076204bcf
Revises: e1f2a3b4c5d6
Create Date: 2026-03-26 15:55:41.374098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3076204bcf'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_change_set',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('changeset_json', sa.Text(), nullable=False),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('staging_status', sa.String(), nullable=False),
    sa.Column('apply_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['import_run.id'], name=op.f('fk_staged_change_set_run_id_import_run'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staged_change_set')),
    sa.UniqueConstraint('run_id', name=op.f('uq_staged_change_set_run_id'))
    )
    op.create_table('standard_snapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('standard_name', sa.String(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['import_run.id'], name=op.f('fk_standard_snapshot_run_id_import_run'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_snapshot')),
    sa.UniqueConstraint('run_id', 'standard_name', name='uq_standard_snapshot_run_standard')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_snapshot')
    op.drop_table('staged_change_set')
    # ### end Alembic commands ###
