"""drop description from uq_node constraint

Revision ID: 7f27babf58e1
Revises: 5029c02946f9
Create Date: 2024-03-24 13:56:58.321752

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f27babf58e1"
down_revision = "5029c02946f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.drop_constraint("uq_node", type_="unique")
        batch_op.create_unique_constraint(
            "uq_node", ["name", "section", "subsection", "version", "section_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.drop_constraint("uq_node", type_="unique")
        batch_op.create_unique_constraint(
            "uq_node",
            [
                "name",
                "section",
                "subsection",
                "ntype",
                "description",
                "version",
                "section_id",
            ],
        )

    # ### end Alembic commands ###
