#!/usr/bin/env python3
"""Generate the harvester's org-wide ``repos.yaml`` from the OWASP GitHub org.

``repos.curated.yaml`` (hand-written, next to ``repos.yaml``) keeps the repos that
need bespoke chunking or paths (ASVS, AISVS, CheatSheetSeries). This script lists
every other non-fork OWASP repo, classifies it by name, and writes
``repos.yaml`` = per-kind defaults + the curated entries verbatim + one compact
line per remaining repo:

  www-chapter-*  -> chapter  (OWASP agent metadata path; never cloned by Module A)
  www-event-*    -> event    (OWASP agent metadata path; never cloned by Module A)
  www-project-*  -> project  (knowledge-graph expansion path)
  everything else-> other    (knowledge-graph expansion path)

Usage:
  GITHUB_TOKEN=$(gh auth token) python scripts/oie_generate_repos_yaml.py
  python scripts/oie_generate_repos_yaml.py --repos-json org_repos.json   # offline

Do not hand-edit ``repos.yaml``; edit ``repos.curated.yaml`` and regenerate.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

HARVESTER_DIR = (
    Path(__file__).resolve().parents[1] / "application" / "utils" / "harvester"
)
DEFAULT_CURATED = HARVESTER_DIR / "repos.curated.yaml"
DEFAULT_OUT = HARVESTER_DIR / "repos.yaml"

_CONTENT_DEFAULTS = """\
    type: github
    owner: OWASP
    paths:
      include:
        - "**/*.md"
      exclude:
        - "**/node_modules/**"
        - "**/vendor/**"
        - "**/.github/**"
        - "**/archive/**"
    chunking:
      strategy: markdown_heading
      max_tokens: 1000
      overlap_tokens: 100
      merge_profile: narrative
    polling:
      mode: incremental
      interval_minutes: 1440
"""

_METADATA_DEFAULTS = """\
    type: github
    owner: OWASP
    paths:
      include:
        - "index.md"
    chunking:
      strategy: markdown_heading
      max_tokens: 1000
    polling:
      mode: full
      interval_minutes: 1440
"""

_HEADER = """\
# GENERATED by scripts/oie_generate_repos_yaml.py -- do not hand-edit.
# Edit repos.curated.yaml for bespoke entries, then regenerate.
defaults:
  project:
{content}  other:
{content}  chapter:
{metadata}  event:
{metadata}"""


def classify_repo(name: str) -> str:
    lowered = name.lower()
    if lowered.startswith("www-chapter-"):
        return "chapter"
    if lowered.startswith("www-event-"):
        return "event"
    if lowered.startswith("www-project-"):
        return "project"
    return "other"


def fetch_org_repos(org: str, token: str) -> List[Dict[str, Any]]:
    repos: List[Dict[str, Any]] = []
    page = 1
    while True:
        request = urllib.request.Request(
            f"https://api.github.com/orgs/{org}/repos?type=public&per_page=100&page={page}",
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
            batch = json.load(response)
        if not batch:
            return repos
        repos.extend(batch)
        page += 1


def _curated_repo_keys(curated_text: str) -> set[str]:
    import yaml

    parsed = yaml.safe_load(curated_text) or {}
    return {
        f"{str(r['owner']).casefold()}/{str(r['repo']).casefold()}"
        for r in parsed.get("repositories", [])
    }


def _curated_body(curated_text: str) -> str:
    lines = curated_text.splitlines()
    for index, line in enumerate(lines):
        if line.strip() == "repositories:":
            return "\n".join(lines[index + 1 :]).rstrip() + "\n"
    raise ValueError("curated file must contain a top-level 'repositories:' line")


def render_repos_yaml(
    org_repos: Iterable[Dict[str, Any]],
    curated_text: str,
    *,
    org: str = "OWASP",
    include_forks: bool = False,
) -> str:
    curated_keys = _curated_repo_keys(curated_text)
    generated: List[str] = []
    seen_ids: set[str] = set()
    for repo in sorted(org_repos, key=lambda r: str(r["name"]).casefold()):
        name = str(repo["name"])
        if repo.get("fork") and not include_forks:
            continue
        if f"{org.casefold()}/{name.casefold()}" in curated_keys:
            continue
        repo_id = f"owasp-{name.lower()}"
        if repo_id in seen_ids:
            continue
        seen_ids.add(repo_id)
        generated.append(
            "  - {"
            + ", ".join(
                f"{key}: {json.dumps(value)}"
                for key, value in (
                    ("id", repo_id),
                    ("kind", classify_repo(name)),
                    ("repo", name),
                    ("branch", repo.get("default_branch") or "main"),
                )
            )
            + "}"
        )
    return (
        _HEADER.format(content=_CONTENT_DEFAULTS, metadata=_METADATA_DEFAULTS)
        + "repositories:\n"
        + _curated_body(curated_text)
        + "\n".join(generated)
        + "\n"
    )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--org", default="OWASP")
    parser.add_argument("--curated", default=str(DEFAULT_CURATED))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument(
        "--repos-json", default="", help="read the org repo list from this JSON file"
    )
    parser.add_argument("--include-forks", action="store_true")
    args = parser.parse_args(argv)

    if args.repos_json:
        org_repos = json.loads(Path(args.repos_json).read_text(encoding="utf-8"))
    else:
        token = os.environ.get("GITHUB_TOKEN", "").strip()
        if not token:
            print("GITHUB_TOKEN is required (or pass --repos-json)", file=sys.stderr)
            return 2
        org_repos = fetch_org_repos(args.org, token)

    text = render_repos_yaml(
        org_repos,
        Path(args.curated).read_text(encoding="utf-8"),
        org=args.org,
        include_forks=args.include_forks,
    )
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
