name: Test-e2e
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Test-e2e
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          cache: 'yarn'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-setuptools \
              python3-virtualenv \
              python3-pip \
              libxml2-dev \
              libxslt-dev
      - name: Install app dependencies
        run: |
          pip install --upgrade pip setuptools
          make install
      - name: Load CRE data
        run: make upstream-sync
      - name: Run Cypress smoke e2e
        run: make e2e
