name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-setuptools \
              python3-virtualenv \
              python3-pip \
              libxml2-dev \
              libxslt-dev 
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          make install-python
      - name: Start services
        run: |
          make start-containers
          make docker-age
          
      - name: Test (Neo4j Backend)
        env:
          GRAPH_DB_TYPE: neo4j
        run: |
          make test
          
      - name: Test (Apache AGE Backend)
        env:
          GRAPH_DB_TYPE: age
        run: |
          make test
          
      - name: Stop services
        if: always()
        run: |
          make docker-neo4j-rm
          make docker-redis-rm
          make docker-age-rm
