name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' 
          cache: 'pip'
      - name: Install python dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y python3-setuptools python3-virtualenv python3-pip
         pip install --upgrade pip
         make install-python
      - name: Test
        run: make test
